### PR TITLE
fix NPE exception when the 'runtimeVersion' is not set

### PR DESCRIPTION
**Pull request by jdubois**
In the Maven plugin, if the `<runtimeVersion>Java8</runtimeVersion>` is not set (which should be the majority of cases, as it's an optional parameter, and as only Java 8 is supported at the moment according to the doc - when in fact Java 11 also works), then you'll get an NPE when doing the regexp on the line below.
This prevents the NPE, and instead gives the default value, which should be the case when nothing is configured.

### CODE REVIEW

**Comment by jdubois** [comment]
BTW I said something wrong, only Java 8 is supported in the plugin... When Java 11 is supported on the platform - do you want another PR for this? There are several things I would like to improve here

**Comment by Flanker32** [comment]
> said something wrong, only Java 8 is supported in the plugin... When Java 11 is supported on the platform - do you want another PR for this? There are several things I would like to

Hi jdubois, java 11 is supported in both service and maven plugin, is there any issue with java 11 runtime in spring maven plugin?

**Comment by jdubois** [comment]
Oh sorry @Flanker32 I must have been on another branch, or distracted: it does support Java 8 and Java 11.
Now what I don't like (and that might have been my original issue in fact), is that it's not the same String as with the `az` command line: it's `Java8` or `java8`, and not `java_8`. Maybe we could accept all 3 options? Anyway, the error message should give the correct possible answers: here it just says it's wrong, and there is no way to know what the correct options are, unless you read the source code.

**Comment by Flanker32** [comment]
@jdubois We are using `Java 8` and `Java 11` as the supported values to be consistent with azure portal, here is the screen shot.
image

I think its better to support both the three cases so that users will not be bothered by the wording, i'll create a pr for this and fix the error message, thanks a lot for your advices.

**Pull request merged**
