### PR TITLE
Update common-configuration.md

### PR DESCRIPTION
**Pull request by alant94**
Noticed this problem when tried to authenticate via azure cli to deploy webapp with plugin "azure-webapp-maven-plugin:1.4.0".
Error says:
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project myproject: java.io.IOException: clientId is null or empty

### CODE REVIEW

**Comment by jdneo** [comment]
Related with https://github.com/Microsoft/azure-maven-plugins/issues/125.

Let me first try to get the response from the SDK team, then we can conclude login through Service Principal is possible or not.

**Comment by alant94** [comment]
Hi @jdneo!
As there are [no answer](https://github.com/Azure/azure-libraries-for-java/issues/417) from the development team for half a year already, maybe it is time to mention it in documentation, so users won't waste time trying to authenticate with SPN?

**Comment by jdneo** [comment]
@alant94 You are right.

I just sent out an email to ask the dev team about this issue. Let's wait for a few days more before we decide to update the docs.

Thanks.

**Comment by alant94** [comment]
@jdneo it is already a month after you sent out an email to ask the dev team about this issue. Since there are no updates maybe it is time to update documentation?

**Comment by jdneo** [comment]
@alant94 

Sorry for the late reply. The PR is merged. Thank you for your contribution!

**Pull request merged**
